# Generated by Django 2.0.5 on 2018-05-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('actid', models.AutoField(primary_key=True, serialize=False, verbose_name='番号')),
                ('actname', models.CharField(blank=True, max_length=255, verbose_name='活動名')),
                ('time', models.DateField(verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='サイト名')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('start', models.DateTimeField(verbose_name='閲覧開始時刻')),
                ('end', models.DateTimeField(verbose_name='閲覧終了時刻')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contents', to='timemaker.Activity', verbose_name='活動')),
            ],
        ),
    ]
