# Generated by Django 2.0.5 on 2018-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='act',
        ),
        migrations.AlterField(
            model_name='contents',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='番号'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
