# Generated by Django 2.0.5 on 2018-06-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemaker', '0002_auto_20180630_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='番号')),
                ('site', models.CharField(blank=True, max_length=255, verbose_name='サイト名')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('date', models.DateField(verbose_name='日付')),
                ('start', models.DateTimeField(verbose_name='閲覧開始時刻')),
                ('end', models.DateTimeField(verbose_name='閲覧終了時刻')),
            ],
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
